version: '3'

services:
  nextjs-tutorial:
    ports:
      - 3000:3000
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/frontend
      # - ./:/usr/src/app/
      - /frontend/node_modules
      # - /usr/src/app/node_modules